//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JJManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] CompatibleDevices {
            get {
                object obj = ResourceManager.GetObject("CompatibleDevices", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] fa_brands_400 {
            get {
                object obj = ResourceManager.GetObject("fa_brands_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] fa_regular_400 {
            get {
                object obj = ResourceManager.GetObject("fa_regular_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] fa_solid_900 {
            get {
                object obj = ResourceManager.GetObject("fa_solid_900", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01 {
            get {
                object obj = ResourceManager.GetObject("JJB-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01_input01 {
            get {
                object obj = ResourceManager.GetObject("JJB-01_input01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01_input01_hover {
            get {
                object obj = ResourceManager.GetObject("JJB-01_input01_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01_input02 {
            get {
                object obj = ResourceManager.GetObject("JJB-01_input02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01_input02_hover {
            get {
                object obj = ResourceManager.GetObject("JJB-01_input02_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01_v2_off {
            get {
                object obj = ResourceManager.GetObject("JJB-01-v2_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01_v2_on {
            get {
                object obj = ResourceManager.GetObject("JJB-01-v2_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_999_off {
            get {
                object obj = ResourceManager.GetObject("JJB-999_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_999_on {
            get {
                object obj = ResourceManager.GetObject("JJB-999_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_Slim_A {
            get {
                object obj = ResourceManager.GetObject("JJB_Slim_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_Slim_A_active {
            get {
                object obj = ResourceManager.GetObject("JJB_Slim_A_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_Slim_A_hover {
            get {
                object obj = ResourceManager.GetObject("JJB_Slim_A_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJBP_06_off {
            get {
                object obj = ResourceManager.GetObject("JJBP-06_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJBP_06_on {
            get {
                object obj = ResourceManager.GetObject("JJBP-06_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJDB01_base {
            get {
                object obj = ResourceManager.GetObject("JJDB01_base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] JJDB01_dashboard_vars {
            get {
                object obj = ResourceManager.GetObject("JJDB01_dashboard_vars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJDB01_led {
            get {
                object obj = ResourceManager.GetObject("JJDB01_led", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJDB01_led_hover {
            get {
                object obj = ResourceManager.GetObject("JJDB01_led_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJM_01 {
            get {
                object obj = ResourceManager.GetObject("JJM-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJM_01_input {
            get {
                object obj = ResourceManager.GetObject("JJM_01_input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJM_01_input_hover {
            get {
                object obj = ResourceManager.GetObject("JJM_01_input_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        /// </summary>
        internal static System.Drawing.Icon JJManagerIcon_256 {
            get {
                object obj = ResourceManager.GetObject("JJManagerIcon_256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] JJPropertyDictionary {
            get {
                object obj = ResourceManager.GetObject("JJPropertyDictionary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJSD_01 {
            get {
                object obj = ResourceManager.GetObject("JJSD-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJSD01_input {
            get {
                object obj = ResourceManager.GetObject("JJSD01_input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJSD01_input_hover {
            get {
                object obj = ResourceManager.GetObject("JJSD01_input_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_JohnJohn_JJMixer {
            get {
                object obj = ResourceManager.GetObject("Logo JohnJohn JJMixer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap options_input {
            get {
                object obj = ResourceManager.GetObject("options_input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_icon {
            get {
                object obj = ResourceManager.GetObject("refresh_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SET XACT_ABORT ON; -- Automatic rollback on error
        ///SET ANSI_WARNINGS OFF;
        ///GO
        ///
        ///DECLARE @schema_name NVARCHAR(256);
        ///DECLARE @table_name NVARCHAR(256);
        ///DECLARE @col_name NVARCHAR(256);
        ///DECLARE @Command NVARCHAR(MAX);
        ///
        ///-- Step 1: Set schema, table, and column names
        ///SET @schema_name = N&apos;dbo&apos;;
        ///SET @table_name = N&apos;analog_inputs&apos;;
        ///SET @col_name = N&apos;axis_orientation&apos;;
        ///
        ///-- Step 2: Dynamically drop default constraint for the column (original name)
        ///SELECT TOP 1 @Command = 
        ///    &apos;ALTER TABLE &apos; + @schema_na [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQL_1_1_14 {
            get {
                return ResourceManager.GetString("SQL_1_1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///UPDATE dbo.configs SET software_version = &apos;1.1.15&apos;;
        ///GO
        ///
        ///SET ANSI_WARNINGS on
        ///GO.
        /// </summary>
        internal static string SQL_1_1_15 {
            get {
                return ResourceManager.GetString("SQL_1_1_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///CREATE TABLE dbo.jj_products (
        ///    id INT IDENTITY (1, 1) NOT NULL,
        ///    product_name VARCHAR (50) NOT NULL,
        ///    analog_inputs_qtd TINYINT NOT NULL DEFAULT 0, 
        ///    digital_inputs_qtd TINYINT NOT NULL DEFAULT 0, 
        ///    CONSTRAINT PK_JJ_PRODUCT PRIMARY KEY CLUSTERED (id ASC)
        ///);
        ///
        ///
        ///CREATE TABLE dbo.digital_inputs
        ///(
        ///    id              INT      NOT NULL,
        ///    name            VARCHAR (15 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQL_1_2_0 {
            get {
                return ResourceManager.GetString("SQL_1_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///UPDATE dbo.configs SET software_version = &apos;1.2.1&apos;;
        ///GO
        ///
        ///SET ANSI_WARNINGS on
        ///GO.
        /// </summary>
        internal static string SQL_1_2_1 {
            get {
                return ResourceManager.GetString("SQL_1_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///IF OBJECT_ID(&apos;dbo.frames&apos;, &apos;U&apos;) IS NULL
        ///BEGIN
        ///    CREATE TABLE [dbo].[frames] (
        ///        [id] BIGINT IDENTITY(1,1) NOT NULL,
        ///        [info] TEXT NOT NULL,
        ///        [num_order] INT NOT NULL,
        ///        [delay] INT DEFAULT 1000 NOT NULL,
        ///        [id_profile] INT NOT NULL,
        ///        CONSTRAINT [PK_FRAME] PRIMARY KEY CLUSTERED ([id] ASC, [id_profile] ASC),
        ///        CONSTRAINT [FK_PROFILE_FRAM [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQL_1_2_2 {
            get {
                return ResourceManager.GetString("SQL_1_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///UPDATE dbo.configs SET software_version = &apos;1.2.3&apos;;
        ///GO
        ///
        ///SET ANSI_WARNINGS on
        ///GO.
        /// </summary>
        internal static string SQL_1_2_3 {
            get {
                return ResourceManager.GetString("SQL_1_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///UPDATE dbo.configs SET software_version = &apos;1.2.3.1&apos;;
        ///GO
        ///
        ///SET ANSI_WARNINGS on
        ///GO.
        /// </summary>
        internal static string SQL_1_2_3_1 {
            get {
                return ResourceManager.GetString("SQL_1_2_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///CREATE TABLE [dbo].[device_inputs] (
        ///    [id]         INT          NOT NULL,
        ///    [name]       VARCHAR (15) NULL,
        ///    [data]       TEXT         NULL,
        ///    [type]       VARCHAR (30) NOT NULL,
        ///	[mode]       VARCHAR (30) NOT NULL,
        ///    [id_profile] INT          NOT NULL,
        ///    CONSTRAINT [PK_DEVICE_INPUT] PRIMARY KEY CLUSTERED ([id] ASC, [id_profile] ASC),
        ///    CONSTRAINT [FK_PROFILE_DEVICE [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQL_1_2_4 {
            get {
                return ResourceManager.GetString("SQL_1_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///ALTER TABLE dbo.jj_products
        ///ADD analog_outputs_qtd TINYINT NOT NULL DEFAULT(0),
        ///    digital_outputs_qtd TINYINT NOT NULL DEFAULT(0),
        ///    conn_type VARCHAR (10) NULL,
        ///    class_name VARCHAR (10) NULL;
        ///GO
        ///
        ///UPDATE dbo.jj_products SET conn_type = &apos;HID&apos;, class_name = &apos;JJM01&apos; WHERE id = 1; -- product_name = &apos;Mixer de �udio JJM-01&apos;;
        ///GO
        ///UPDATE dbo.jj_products SET conn_type = &apos;Joystick&apos;, c [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQL_1_2_5 {
            get {
                return ResourceManager.GetString("SQL_1_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///UPDATE dbo.configs SET software_version = &apos;1.2.6&apos;;
        ///GO
        ///
        ///SET ANSI_WARNINGS on
        ///GO.
        /// </summary>
        internal static string SQL_1_2_6 {
            get {
                return ResourceManager.GetString("SQL_1_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///UPDATE dbo.configs SET software_version = &apos;1.2.6.1&apos;;
        ///GO
        ///
        ///SET ANSI_WARNINGS on
        ///GO.
        /// </summary>
        internal static string SQL_1_2_6_1 {
            get {
                return ResourceManager.GetString("SQL_1_2_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///UPDATE dbo.configs SET software_version = &apos;1.2.7&apos;;
        ///GO
        ///
        ///SET IDENTITY_INSERT dbo.jj_products ON;
        ///GO
        ///
        ///INSERT INTO dbo.jj_products (id, product_name, analog_inputs_qtd, digital_inputs_qtd, analog_outputs_qtd, digital_outputs_qtd, conn_type, class_name) VALUES 
        ///(14, &apos;LoadCell JJLC-01&apos;, 0, 0, 0, 0, &apos;HID&apos;, &apos;JJLC01&apos;);
        ///GO
        ///
        ///UPDATE dbo.jj_products set digital_outputs_qtd = 255 WHERE product [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQL_1_2_7 {
            get {
                return ResourceManager.GetString("SQL_1_2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///UPDATE dbo.configs SET software_version = &apos;1.2.8&apos;;
        ///GO
        ///
        ///IF NOT EXISTS (
        ///    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
        ///    WHERE TABLE_NAME = &apos;simhub_properties&apos; AND COLUMN_NAME = &apos;activate_on&apos;
        ///)
        ///BEGIN
        ///    ALTER TABLE simhub_properties 
        ///    ADD activate_on NVARCHAR(MAX) 
        ///        CONSTRAINT DF_SIMHUB_PROPERTIES_ACTIVATE_ON DEFAULT &apos;{}&apos; 
        ///        CHECK (ISJSON(activate_on) &gt; 0);
        ///END [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQL_1_2_8 {
            get {
                return ResourceManager.GetString("SQL_1_2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///ALTER TABLE simhub_properties
        ///ALTER COLUMN simhub_prop VARCHAR(255) NULL;
        ///GO
        ///
        ///IF EXISTS (
        ///    SELECT 1
        ///    FROM INFORMATION_SCHEMA.COLUMNS
        ///    WHERE TABLE_NAME = &apos;simhub_properties&apos;
        ///      AND COLUMN_NAME = &apos;activated_on&apos;
        ///)
        ///BEGIN
        ///    ALTER TABLE simhub_properties
        ///    DROP CONSTRAINT DF_SIMHUB_PROPERTIES_ACTIVATED_ON;
        ///
        ///    ALTER TABLE simhub_properties
        ///    DROP CONSTRAINT CK__ [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQL_1_2_9 {
            get {
                return ResourceManager.GetString("SQL_1_2_9", resourceCulture);
            }
        }
    }
}
