//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JJManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01 {
            get {
                object obj = ResourceManager.GetObject("JJB-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01_input01 {
            get {
                object obj = ResourceManager.GetObject("JJB-01_input01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01_input01_hover {
            get {
                object obj = ResourceManager.GetObject("JJB-01_input01_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01_input02 {
            get {
                object obj = ResourceManager.GetObject("JJB-01_input02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJB_01_input02_hover {
            get {
                object obj = ResourceManager.GetObject("JJB-01_input02_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJM_01 {
            get {
                object obj = ResourceManager.GetObject("JJM-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJM_01_input {
            get {
                object obj = ResourceManager.GetObject("JJM_01_input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JJM_01_input_hover {
            get {
                object obj = ResourceManager.GetObject("JJM_01_input_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        /// </summary>
        internal static System.Drawing.Icon JJManagerIcon_256 {
            get {
                object obj = ResourceManager.GetObject("JJManagerIcon_256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_JohnJohn_JJMixer {
            get {
                object obj = ResourceManager.GetObject("Logo JohnJohn JJMixer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap options_input {
            get {
                object obj = ResourceManager.GetObject("options_input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_icon {
            get {
                object obj = ResourceManager.GetObject("refresh_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///--BEGIN TRANSACTION _1_1_14
        ///
        ///declare @schema_name nvarchar(256)
        ///declare @table_name nvarchar(256)
        ///declare @col_name nvarchar(256)
        ///declare @Command  nvarchar(1000)
        ///
        ///set @schema_name = N&apos;dbo&apos;
        ///set @table_name = N&apos;analog_inputs&apos;
        ///set @col_name = N&apos;axis_orientation&apos;
        ///
        ///select @Command = &apos;ALTER TABLE &apos; + @schema_name + &apos;.[&apos; + @table_name + &apos;] DROP CONSTRAINT &apos; + d.name
        /// from sys.tables  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQL_1_1_14 {
            get {
                return ResourceManager.GetString("SQL_1_1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///UPDATE dbo.configs SET software_version = &apos;1.1.15&apos;;
        ///GO
        ///
        ///SET ANSI_WARNINGS on
        ///GO.
        /// </summary>
        internal static string SQL_1_1_15 {
            get {
                return ResourceManager.GetString("SQL_1_1_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -- Automaticamente da Rollback quando acontece um erro na transaction.
        ///set xact_abort on
        ///SET ANSI_WARNINGS off
        ///GO
        ///
        ///CREATE TABLE dbo.jj_products (
        ///    id INT IDENTITY (1, 1) NOT NULL,
        ///    product_name VARCHAR (50) NOT NULL,
        ///    analog_inputs_qtd TINYINT NOT NULL DEFAULT 0, 
        ///    digital_inputs_qtd TINYINT NOT NULL DEFAULT 0, 
        ///    CONSTRAINT PK_JJ_PRODUCT PRIMARY KEY CLUSTERED (id ASC)
        ///);
        ///
        ///
        ///CREATE TABLE dbo.digital_inputs
        ///(
        ///    id              INT      NOT NULL,
        ///    name            VARCHAR (15 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQL_1_2_0 {
            get {
                return ResourceManager.GetString("SQL_1_2_0", resourceCulture);
            }
        }
    }
}
